### PR TITLE
Trap non-zero process return values in _run_minizinc

### LINKED ISSUE #54: Handling numerical Issues in model
When model contains numbers >= typemax(Int32), I noticed some strange behaviors. Check the following simple model:

- x * large_n + y > rhs
- x,y in [0,10]

large_n = typemax(Int32)

**Issue 1:**
if we set rhs = large_n, I got an error msg:

ERROR: LoadError: MathOptInterface.UnsupportedConstraint{MathOptInterface.ScalarNonlinearFunction, MathOptInterface.GreaterThan{Int32}}: `MathOptInterface.ScalarNonlinearFunction`-in-`MathOptInterface.GreaterThan{Int32}` constraint is not supported by the model.

However, the error'd disappear if we set rhs to something even bigger e.g., 2*large_n?

**Issue 2:**
When we set rhs = 2*large_n, it returns MOI.OPTIMAL

`var 1 .. 10: x1;
var 1 .. 10: x2;
constraint ((x1 * 2147483647) + x2) >= 4294967294;
solve satisfy;`

But, if we set large_n = typemax(Int32) + 2, it returns MOI.INFEASIBLE

`var 1 .. 10: x1;
var 1 .. 10: x2;
constraint ((x1 * 2147483649) + x2) >= 4294967298;
solve satisfy;`

Looks like the solver (chuffed) can't handle these large numbers. Should we always warn user when there is numerical issue in the model? What error message'd be appropriate?

Repro:

```
function test_moi_numerical_issue()
    model = MOI.Utilities.Model{Int}()
    x, _= MOI.add_constrained_variable(model, MOI.Integer())
    y, _= MOI.add_constrained_variable(model, MOI.Integer())
    MOI.add_constraint(model, x, MOI.Interval(1, 10))
    MOI.add_constraint(model, y, MOI.Interval(1, 10))
    large_n = typemax(Int32) 
    snf1 = MOI.ScalarNonlinearFunction(:*, Any[x, large_n])
    rhs = large_n
    c1 = MOI.add_constraint(model, MOI.ScalarNonlinearFunction(:+, Any[snf1, y]), MOI.GreaterThan(rhs))
    optimizer = MiniZinc.Optimizer{Int}("chuffed")
    index_map,_ = MOI.optimize!(optimizer, model)
    @test MOI.get(optimizer, MOI.TerminationStatus()) === MOI.INFEASIBLE
    @test MOI.get(optimizer, MOI.ResultCount()) == 0
    @test MOI.get(optimizer, MOI.RawStatusString()) == "UNSATISFIABLE"
end
```

### PR DESCRIPTION
**Pull request by odow**
Closes #54

### CODE REVIEW

File: src/optimize.jl [hunk 1]
```diff
@@ -232,22 +241,22 @@ function MOI.is_valid(model::Optimizer, x::MOI.VariableIndex)
...
-    return model.solver_status == "SATISFIABLE" &&
+    return model.solver_status == "=====SATISFIABLE=====" &&
            !isempty(model.primal_solutions)
 end
 
 MOI.get(model::Optimizer, ::MOI.RawStatusString) = model.solver_status
 
 function MOI.get(model::Optimizer, ::MOI.TerminationStatus)
-    if model.solver_status == "UNSATISFIABLE"
+    if occursin("=UNSATISFIABLE=", model.solver_status)
```
Comment (odow) [inline src/optimize.jl:251]:
```suggestion
    if occursin("UNSATISFIABLE", model.solver_status)
```

File: src/optimize.jl [hunk 2]
```diff
@@ -232,22 +241,22 @@ function MOI.is_valid(model::Optimizer, x::MOI.VariableIndex)
...
         return MOI.INFEASIBLE
     elseif _has_solution(model)
         if 1 < model.options["num_solutions"] <= length(model.primal_solutions)
             return MOI.SOLUTION_LIMIT
         else
             return MOI.OPTIMAL
         end
-    elseif model.solver_status == "UNKNOWN" &&
+    elseif occursin("UNKNONWN", model.solver_status) &&
```
Comment (odow) [inline src/optimize.jl:259]:
```suggestion
    elseif occursin("UNKNOWN", model.solver_status) &&
```

File: src/optimize.jl [hunk 3]
```diff
@@ -196,9 +205,9 @@ function MOI.optimize!(dest::Optimizer{T}, src::MOI.ModelLike) where {T}
         m_stat = match(r"=====(.+)=====", ret)
         if m_stat !== nothing
             @assert length(m_stat.captures) == 1
-            dest.solver_status = m_stat[1]
+            dest.solver_status = ret
         else
-            dest.solver_status = "SATISFIABLE"
+            dest.solver_status = "=====SATISFIABLE====="
```
Comment (odow) [inline src/optimize.jl:210]:
```suggestion
            dest.solver_status = "SATISFIABLE"
```

File: src/optimize.jl [hunk 4]
```diff
@@ -232,22 +241,22 @@ function MOI.is_valid(model::Optimizer, x::MOI.VariableIndex)
 end
 
 function _has_solution(model::Optimizer)
-    return model.solver_status == "SATISFIABLE" &&
+    return model.solver_status == "=====SATISFIABLE=====" &&
```
Comment (odow) [inline src/optimize.jl:244]:
```suggestion
    return model.solver_status == "SATISFIABLE" &&
```

File: src/optimize.jl [hunk 5]
```diff
@@ -196,9 +205,9 @@ function MOI.optimize!(dest::Optimizer{T}, src::MOI.ModelLike) where {T}
         m_stat = match(r"=====(.+)=====", ret)
         if m_stat !== nothing
             @assert length(m_stat.captures) == 1
-            dest.solver_status = m_stat[1]
+            dest.solver_status = ret
```
Comment (odow) [inline src/optimize.jl:208]:
```suggestion
            dest.solver_status = occursin("ERROR", ret) ? ret : m_stat[1]
```
